# Generated by Django 3.1.2 on 2020-11-20 18:23

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0001_initial_squashed_0010_auto_20201113_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentArchives',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=40)),
                ('MiddleName', models.CharField(blank=True, max_length=40)),
                ('LastName', models.CharField(max_length=40)),
                ('Email', models.CharField(blank=True, max_length=30)),
                ('PhoneNumber', models.CharField(max_length=50)),
                ('Status', models.IntegerField(default=1)),
                ('UserSavedBy', models.IntegerField(default=0)),
                ('StatusChangedBy', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=746, multiple=True)),
            ],
        ),
    ]
